// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DiKVClient is the client API for DiKV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiKVClient interface {
	// Put a kv pair
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutReply, error)
	// Get a value by key
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
}

type diKVClient struct {
	cc grpc.ClientConnInterface
}

func NewDiKVClient(cc grpc.ClientConnInterface) DiKVClient {
	return &diKVClient{cc}
}

func (c *diKVClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutReply, error) {
	out := new(PutReply)
	err := c.cc.Invoke(ctx, "/dikv.DiKV/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diKVClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, "/dikv.DiKV/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiKVServer is the server API for DiKV service.
// All implementations must embed UnimplementedDiKVServer
// for forward compatibility
type DiKVServer interface {
	// Put a kv pair
	Put(context.Context, *PutRequest) (*PutReply, error)
	// Get a value by key
	Get(context.Context, *GetRequest) (*GetReply, error)
	mustEmbedUnimplementedDiKVServer()
}

// UnimplementedDiKVServer must be embedded to have forward compatible implementations.
type UnimplementedDiKVServer struct {
}

func (UnimplementedDiKVServer) Put(context.Context, *PutRequest) (*PutReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedDiKVServer) Get(context.Context, *GetRequest) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDiKVServer) mustEmbedUnimplementedDiKVServer() {}

// UnsafeDiKVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiKVServer will
// result in compilation errors.
type UnsafeDiKVServer interface {
	mustEmbedUnimplementedDiKVServer()
}

func RegisterDiKVServer(s grpc.ServiceRegistrar, srv DiKVServer) {
	s.RegisterService(&DiKV_ServiceDesc, srv)
}

func _DiKV_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiKVServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dikv.DiKV/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiKVServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiKV_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiKVServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dikv.DiKV/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiKVServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiKV_ServiceDesc is the grpc.ServiceDesc for DiKV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiKV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dikv.DiKV",
	HandlerType: (*DiKVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _DiKV_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DiKV_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dikv.proto",
}
